name: CI/CD Microservices

on:
  push:
    branches:
      - dev # Thay đổi nếu bạn dùng branch khác

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build -t dttrung324/react-ci-cd:latest .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push dttrung324/react-ci-cd:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull dttrung324/react-ci-cd:latest
            docker stop react-ci-cd-container || true
            docker rm react-ci-cd-container || true
            docker run -d -p 3000:3000 --name react-ci-cd-container dttrung324/react-ci-cd:latest